import { createTodoCard } from '../components/todoCard';
import { createButton } from '../components/button';
import { createModal } from '../components/modal';
import { createTodoForm } from '../components/todoForm';
import { createDropdown } from '../components/dropdown';
import { ListFilter, Plus, ArrowUpDown } from 'lucide';
import autoAnimate from '@formkit/auto-animate';

/**
 * @param {Array} todos - an array of todo objects generated by the user from the todo model
 */

function projectView(
  todos = [],
  projectName,
  onToggle,
  onDelete,
  onAddTodo,
  onDeleteTodo,
) {
  const contentWrapper = document.querySelector('.content');
  contentWrapper.innerHTML = '';

  // project view wrapper
  const projectWrapper = document.createElement('div');
  projectWrapper.classList.add('project-wrapper');

  // page header with project name
  const pageHeader = document.createElement('div');
  pageHeader.classList.add('page-header');
  const title = document.createElement('h2');
  title.textContent = projectName;

  // filter and sort helper function
  let currentFilter = []; // empty array = show all priorities
  let currentSort = 'default'; // 'default', 'dueDate', 'priority'

  const getFilteredAndSortedTodos = () => {
    let result = todos.filter((todo) => !todo.getStatus());

    // apply priority filter if any selected
    if (currentFilter.length > 0) {
      result = result.filter((todo) =>
        currentFilter.includes(todo.getPriority().toLowerCase()),
      );
    }

    // apply sort
    if (currentSort === 'dueDate') {
      result.sort(
        (a, b) => new Date(b.getDueDate()) - new Date(a.getDueDate()),
      );
    } else if (currentSort === 'priority') {
      const order = { high: 0, medium: 1, low: 2 };
      result.sort(
        (a, b) =>
          order[a.getPriority().toLowerCase()] -
          order[b.getPriority().toLowerCase()],
      );
    }

    return result;
  };

  // filter and sort dropdowns
  const filterSortContainer = document.createElement('div');
  filterSortContainer.classList.add('filter-sort-container');

  const filterDropdown = createDropdown({
    label: 'Filter',
    options: [
      { label: 'High', value: 'high' },
      { label: 'Medium', value: 'medium' },
      { label: 'Low', value: 'low' },
    ],
    multiSelect: true,
    onChange: (values) => {
      currentFilter = values;
      renderTodos(); // re-render with new filter
    },
    icon: ListFilter,
  });

  const sortDropdown = createDropdown({
    label: 'Sort',
    options: [
      { label: 'Default', value: 'default' },
      { label: 'Due Date', value: 'dueDate' },
      { label: 'Priority', value: 'priority' },
    ],
    onChange: (value) => {
      currentSort = value;
      renderTodos(); // re-render with new filter
    },
    icon: ArrowUpDown,
  });

  filterSortContainer.append(filterDropdown, sortDropdown);
  pageHeader.append(title, filterSortContainer);

  // active todos list
  const activeListContainer = document.createElement('div');
  activeListContainer.classList.add('todo-list');
  autoAnimate(activeListContainer);

  // all completed message - sibling of activeListContainer, not inside it
  const completedMessage = document.createElement('p');
  completedMessage.textContent = 'All todos completed! Time to chill out.';
  completedMessage.style.display = 'none';
  completedMessage.classList.add('completed-message');

  // completed section - title is separate from the animated list
  const completedSection = document.createElement('div');
  completedSection.classList.add('completed-section');
  const completedTitle = document.createElement('h3');
  completedTitle.textContent = 'Completed todo items';
  completedTitle.style.display = 'none';
  const completedListContainer = document.createElement('div');
  completedListContainer.classList.add('todo-list', 'completed');
  autoAnimate(completedListContainer);
  completedSection.append(completedTitle, completedListContainer);

  // wrap onToggle to also update completed title visibility
  const handleToggle = (todo, card, activeList, completedList) => {
    onToggle(todo, card, activeList, completedList);
    completedTitle.style.display =
      completedListContainer.children.length > 0 ? 'block' : 'none';
    if (activeListContainer.querySelectorAll('.todo-card').length === 0) {
      completedMessage.style.display = 'block';
    } else {
      completedMessage.style.display = 'none';
    }
  };

  // render todos or empty message
  if (todos.length === 0) {
    const emptyMessage = document.createElement('p');
    emptyMessage.textContent = 'No todos yet. Add one! Or chill out.';
    emptyMessage.classList.add('empty-message');
    activeListContainer.appendChild(emptyMessage);
  } else {
    todos.forEach((todo) => {
      const card = createTodoCard(
        todo,
        handleToggle,
        activeListContainer,
        completedListContainer,
        onDeleteTodo,
      );
      if (!todo.getStatus()) {
        activeListContainer.appendChild(card);
      } else {
        completedListContainer.appendChild(card);
      }
    });
  }

  // set initial visibility of completed title
  completedTitle.style.display =
    completedListContainer.children.length > 0 ? 'block' : 'none';

  // render todos after filter or sort changes
  const renderTodos = () => {
    autoAnimate(activeListContainer, { duration: 0 }); // disable animation
    activeListContainer.innerHTML = '';
    const filtered = getFilteredAndSortedTodos();

    if (filtered.length === 0) {
      const emptyMessage = document.createElement('p');
      emptyMessage.textContent = 'No todos match your filters.';
      emptyMessage.classList.add('empty-message');
      activeListContainer.appendChild(emptyMessage);
    } else {
      filtered.forEach((todo) => {
        const card = createTodoCard(
          todo,
          handleToggle,
          activeListContainer,
          completedListContainer,
          onDeleteTodo,
        );
        activeListContainer.appendChild(card);
      });
    }
    autoAnimate(activeListContainer); // re-enable with default duration
  };

  // delete project modal content
  const deleteBtnContent = document.createElement('div');
  deleteBtnContent.classList.add('delete-project-content');
  const deleteMessage = document.createElement('p');
  deleteMessage.textContent =
    'Are you sure you want to delete this project? This action cannot be undone.';
  deleteBtnContent.appendChild(deleteMessage);

  // create delete project modal and ensure only one exists at a time
  const existingModal = document.querySelector('.modal.delete-project-modal');
  if (existingModal) existingModal.remove();

  const deleteProjectModal = createModal('Delete Project', deleteBtnContent);
  deleteProjectModal.classList.add('delete-project-modal');

  // modal buttons
  const deleteProjectBtnContainer = document.createElement('div');
  deleteProjectBtnContainer.classList.add('form-actions');

  const cancelBtn = createButton({
    label: 'Cancel',
    classes: ['btn-ghost'],
    onClick: (e) => {
      e.preventDefault();
      deleteProjectModal.close();
    },
  });

  const deleteBtn = createButton({
    label: 'Delete',
    classes: ['btn-danger'],
    onClick: (e) => {
      e.preventDefault();
      deleteProjectModal.close();
      onDelete();
    },
  });

  deleteProjectBtnContainer.append(cancelBtn, deleteBtn);
  deleteProjectModal.appendChild(deleteProjectBtnContainer);
  document.body.appendChild(deleteProjectModal);

  // delete project button
  const deleteProjectBtn = createButton({
    label: 'Delete Project',
    classes: ['btn-danger', 'btn-delete-project'],
    onClick: () => {
      deleteProjectModal.showModal();
    },
  });

  // create add todo modal
  const existingTodoModal = document.querySelector('.modal.create-todo-modal');
  if (existingTodoModal) existingTodoModal.remove();

  const todoFormModal = createTodoForm(onAddTodo);
  todoFormModal.classList.add('create-todo-modal');
  document.body.appendChild(todoFormModal);

  // add todo button
  const addTodoBtn = createButton({
    label: 'Add Todo',
    classes: ['btn', 'btn-secondary'],
    icon: Plus,
    onClick: () => {
      todoFormModal.showModal();
    },
  });

  // button container for delete project and add todo buttons
  const projectBtnContainer = document.createElement('div');
  projectBtnContainer.classList.add('form-actions');
  projectBtnContainer.appendChild(deleteProjectBtn);
  projectBtnContainer.appendChild(addTodoBtn);

  // assemble project wrapper and append to content
  projectWrapper.append(
    pageHeader,
    completedMessage,
    activeListContainer,
    completedSection,
    projectBtnContainer,
  );

  contentWrapper.append(projectWrapper);
}

export default projectView;
