import { createTodoCard } from '../components/todoCard';
import { createButton } from '../components/button';
import { createModal } from '../components/modal';
import autoAnimate from '@formkit/auto-animate';

/**
 * @param {Array} todos - an array of todo objects generated by the user from the todo model
 */

function projectView(todos = [], projectName, onToggle, onDelete) {
  const contentWrapper = document.querySelector('.content');
  contentWrapper.innerHTML = '';

  // project view wrapper
  const projectWrapper = document.createElement('div');
  projectWrapper.classList.add('project-wrapper');

  // page header with project name
  const pageHeader = document.createElement('div');
  pageHeader.classList.add('page-header');
  const title = document.createElement('h2');
  title.textContent = projectName;
  pageHeader.appendChild(title);

  // active todos list
  const activeListContainer = document.createElement('div');
  activeListContainer.classList.add('todo-list');
  autoAnimate(activeListContainer);

  // all completed message - sibling of activeListContainer, not inside it
  const completedMessage = document.createElement('p');
  completedMessage.textContent = 'All todos completed! Time to chill out.';
  completedMessage.style.display = 'none';

  // completed section - title is separate from the animated list
  const completedSection = document.createElement('div');
  completedSection.classList.add('completed-section');
  const completedTitle = document.createElement('h3');
  completedTitle.textContent = 'Completed todo items';
  completedTitle.style.display = 'none';
  const completedListContainer = document.createElement('div');
  completedListContainer.classList.add('todo-list', 'completed');
  autoAnimate(completedListContainer);
  completedSection.append(completedTitle, completedListContainer);

  // wrap onToggle to also update completed title visibility
  const handleToggle = (todo, card, activeList, completedList) => {
    onToggle(todo, card, activeList, completedList);
    completedTitle.style.display =
      completedListContainer.children.length > 0 ? 'block' : 'none';
    if (activeListContainer.querySelectorAll('.todo-card').length === 0) {
      completedMessage.style.display = 'block';
    } else {
      completedMessage.style.display = 'none';
    }
  };

  // render todos or empty message
  if (todos.length === 0) {
    const emptyMessage = document.createElement('p');
    emptyMessage.textContent = 'No todos yet. Add one! Or chill out.';
    activeListContainer.appendChild(emptyMessage);
  } else {
    todos.forEach((todo) => {
      const card = createTodoCard(
        todo,
        handleToggle,
        activeListContainer,
        completedListContainer,
      );
      if (!todo.getStatus()) {
        activeListContainer.appendChild(card);
      } else {
        completedListContainer.appendChild(card);
      }
    });
  }

  // set initial visibility of completed title
  completedTitle.style.display =
    completedListContainer.children.length > 0 ? 'block' : 'none';

  // delete project modal content
  const deleteBtnContent = document.createElement('div');
  deleteBtnContent.classList.add('delete-project-content');
  const deleteMessage = document.createElement('p');
  deleteMessage.textContent =
    'Are you sure you want to delete this project? This action cannot be undone.';
  deleteBtnContent.appendChild(deleteMessage);

  // create delete project modal and ensure only one exists at a time
  const existingModal = document.querySelector('.modal.delete-project-modal');
  if (existingModal) existingModal.remove();

  const deleteProjectModal = createModal('Delete Project', deleteBtnContent);
  deleteProjectModal.classList.add('delete-project-modal');

  // modal buttons
  const deleteProjectBtnContainer = document.createElement('div');
  deleteProjectBtnContainer.classList.add('form-actions');

  const cancelBtn = createButton({
    label: 'Cancel',
    classes: ['btn-ghost'],
    onClick: (e) => {
      e.preventDefault();
      deleteProjectModal.close();
    },
  });

  const deleteBtn = createButton({
    label: 'Delete',
    classes: ['btn-danger'],
    onClick: (e) => {
      e.preventDefault();
      deleteProjectModal.close();
      onDelete();
    },
  });

  deleteProjectBtnContainer.append(cancelBtn, deleteBtn);
  deleteProjectModal.appendChild(deleteProjectBtnContainer);
  document.body.appendChild(deleteProjectModal);

  // delete project button
  const deleteProjectBtn = createButton({
    label: 'Delete Project',
    classes: ['btn-danger', 'btn-delete-project'],
    onClick: () => {
      deleteProjectModal.showModal();
    },
  });

  const projectBtnContainer = document.createElement('div');
  projectBtnContainer.classList.add('form-actions');
  projectBtnContainer.appendChild(deleteProjectBtn);

  // assemble project wrapper and append to content
  projectWrapper.append(
    pageHeader,
    completedMessage,
    activeListContainer,
    completedSection,
    projectBtnContainer,
  );

  contentWrapper.append(projectWrapper);
}

export default projectView;
