import { createTodoCard } from '../components/todoCard';

/**
 * @param {Array} todos - an array of todo objects generated by the user from the todo model
 */

function todosPage(todos = []) {
  let contentWrapper = document.querySelector('.content');
  contentWrapper.innerHTML = '';

  const pageHeader = document.createElement('div');
  pageHeader.classList.add('page-header');

  const title = document.createElement('h2');
  title.textContent = 'My Todos';
  pageHeader.appendChild(title);

  const listContainer = document.createElement('div');
  listContainer.classList.add('todo-list');

  // if there are no todos, show a message
  if (todos.length === 0) {
    const emptyMessage = document.createElement('p');
    emptyMessage.textContent = 'No todos yet. Add one! Or chill out.';
    listContainer.appendChild(emptyMessage);
  } else {
    // loop through the data and use the createTodoCard component to create the cards
    todos.forEach((todo) => {
      const card = createTodoCard(todo);
      listContainer.appendChild(card);
    });
  }

  contentWrapper.append(pageHeader, listContainer);
  pageHeader.appendChild(title);
}

export default todosPage;
